### ISSUE TITLE
type assertion are a TypeScript only feature. Convert your file to a TypeScript file or remove the syntax.🐛 

### ISSUE THREAD

**Issue by kwihpe** [biomejs/biome#2259] opened 2024-03-28 21:03 UTC
### VS Code version

1.87.2

### Extension version

2.2.2

### Biome version

1.6.1

### Operating system

- [ ] Windows
- [X] macOS
- [ ] Linux

### Description

I have a react application, biome is stating that the javascript files have the following issue:
"type assertion are a TypeScript only feature. Convert your file to a TypeScript file or remove the syntax."
It is highlighting the returned elements of the function which are normal JSX.

Biome is even highlight this with the error above: 
`return <div></div>`;

The Biome extension in VS code is the issue, we have Biome running with our pre-commit husky hook and everything is normal. 

### Steps to reproduce

I cannot share the code. 

### Expected behavior

Biome does not mention typescript errors as this is just a javascript project and file. 

### Does this issue occur when using the CLI directly?

Not sure / Not applicable

**Comment by nhedger** [comment] 2024-04-01 07:17
Closing as duplicate of https://github.com/biomejs/biome/issues/2085

**Closed by nhedger** 2024-04-01 07:17 UTC
