### ISSUE TITLE
🐛 nested extends is not working

### ISSUE THREAD

**Issue by unional** [biomejs/biome#2257] opened 2024-04-01 01:05 UTC
### Environment information

```block
CLI:
  Version:                      1.6.3
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.10.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "pnpm/8.15.4"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### What happened?

project-a:

```jsonc
// biome.json
{
  "extends": ["@repobuddy/biome/performant.json"]
  //...
}
```

```jsonc
// @repobuddy/biome/performant.json
{
  "extends": ["./recommended.json"],
  // ...
}
```

```jsonc
// @repobuddy/biome/recommended.json
{
  // ...
}
```

This configuration does not pickup the config in `recommended.json`.
It seems like the `extends` feature only works for one level.

To workaround this, I'll need to copy the content in `recommended.json` to `performant.json` and maintain two (or more) copies.

### Expected result

The resolution works recursively.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment] 2024-04-01 05:46
Duplicate of https://github.com/biomejs/biome/issues/1867

**Closed** 2024-04-01 05:46 UTC
