### ISSUE TITLE
🐛 Android platform support (termux)

### ISSUE THREAD

**Issue by sebastianjnuwu** [biomejs/biome#1340] opened 2023-12-25 19:01 UTC
### Environment information

```block
OS: Android 8.1.0 armv7l
```

### What happened?

I try to run the biome in termux but it seems that the CLI does not support Android, I am running it in termux. Is there really no support for Android or is it my mistake? If there is no support, will there be?

### Expected result

That the CLI worked in termux 

### Code of Conduct

- [x] I agree to follow Biome's Code of Conduct

**Comment by sebastianjnuwu** [comment] 2023-12-25 19:03
![Uploading Screenshot_20231225-154741~2.jpg…]()

**Comment by sebastianjnuwu** [comment] 2023-12-25 19:05
![Screenshot_20231225-154741~2](https://github.com/biomejs/biome/assets/101356556/fb8245c8-7e7d-4fd2-a8fa-5e32b6d5a01b)
![Screenshot_20231225-160340~2](https://github.com/biomejs/biome/assets/101356556/ece13d8d-614d-4945-820b-a58fef579751)

**Comment by sebastianjnuwu** [comment] 2023-12-25 23:36
https://github.com/rust-lang/rust/issues/119306

**Comment by saethlin** [comment] 2023-12-27 19:00
Can you explain how this issue is related to https://github.com/rust-lang/rust/issues/119306? We already explained there that Rust supports Android targets, we just don't automatically build releases that support termux as a host.

**Comment by sebastianjnuwu** [comment] 2023-12-27 21:02
> Você pode explicar como esse problema está relacionado a [rust-lang/rust#119306](https://github.com/rust-lang/rust/issues/119306) ? Já explicamos lá que Rust suporta alvos Android, apenas não construímos automaticamente versões que suportam termux como host.

For the biome to work on my device, it has to have the binaries of my platform, right? And to do that you need to build it. Is this how the problem is related, or am I making something wrong?

**Comment by saethlin** [comment] 2023-12-27 21:09
Rust supports building executables that run on Android/termux. We just do not distribute compilers that run on Android/termux. You can run the compiler on another platform and using `--target` have it generate artifacts that work on Android. This is generally called cross-compilation and is normal for mobile development.

**Comment by ematipico** [comment] 2024-03-04 09:21
I am going to close this issue, because it's not a bug. It's an enhancement that requires tooling to build Biome for this specific platform. If someone wants to help, you're welcome to submit an discussion/PR

**Closed by ematipico** 2024-03-04 09:21 UTC
