### ISSUE TITLE
Organize imports incorrect, deleted one and duplicate one

### ISSUE THREAD

**Issue by zhoujian-official** [biomejs/biome#1595] opened 2024-01-19 02:57 UTC
### Environment information

```block
CLI:
  Version:                      1.5.2
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.11.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.2.4"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true
```

### What happened?

Original code:
import { useState } from "react";
import viteLogo from "/vite.svg";
import reactLogo from "./assets/react.svg";
import "./App.css";

After format:
import { useState } from "react";
import viteLogo from "/vite.svg";
import App.css
import reactLogo from reaassets/react.svgfrom "./assets/react.svg";

The last line of output is broken.

I tried [Playground](https://biomejs.dev/playground/?indentStyle=space&code=aQBtAHAAbwByAHQAIAB7ACAAdQBzAGUAUwB0AGEAdABlACAAfQAgAGYAcgBvAG0AIAAiAHIAZQBhAGMAdAAiADsACgBpAG0AcABvAHIAdAAgAHYAaQB0AGUATABvAGcAbwAgAGYAcgBvAG0AIAAiAC8AdgBpAHQAZQAuAHMAdgBnACIAOwAKAGkAbQBwAG8AcgB0ACAAcgBlAGEAYwB0AEwAbwBnAG8AIABmAHIAbwBtACAAIgAuAC8AYQBzAHMAZQB0AHMALwByAGUAYQBjAHQALgBzAHYAZwAiADsACgBpAG0AcABvAHIAdAAgACIALgAvAEEAcABwAC4AYwBzAHMAIgA7AAoA), but it works fine on playground.

### Expected result

It should output the same as in playground.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment] 2024-01-19 07:06
Probably duplicate of https://github.com/biomejs/biome/issues/1570

Can you confirm that this is an issue that happens ONLY with VSCode?

**Comment by ematipico** [comment] 2024-01-19 07:30
Closing as duplicate

**Closed by ematipico** 2024-01-19 07:30 UTC
