### ISSUE TITLE
💅 `noUndeclaredDependencies` reports `declare module '*.extension'`

### ISSUE THREAD

**Issue by ipanasenko** [biomejs/biome#2123] opened 2024-03-18 13:01 UTC
### Environment information

```bash
CLI:
  Version:                      1.6.1
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v18.19.1"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.2.4"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Linter:
  Recommended:                  true
  All:                          false
  Rules:                        a11y/noSvgWithoutTitle = "off"
                                a11y/useKeyWithClickEvents = "off"
                                a11y/useKeyWithMouseEvents = "off"
                                a11y/useValidAnchor = "off"
                                complexity/noUselessLoneBlockStatements = "error"
                                correctness/noInvalidUseBeforeDeclaration = "off"
                                correctness/noNewSymbol = "error"
                                correctness/noUnusedPrivateClassMembers = "error"
                                correctness/noUnusedVariables = "error"
                                correctness/useExhaustiveDependencies = "off"
                                correctness/useHookAtTopLevel = "error"
                                nursery/noDoneCallback = "error"
                                nursery/noExportsInTest = "error"
                                nursery/noSemicolonInJsx = "error"
                                nursery/noUndeclaredDependencies = "error"
                                nursery/noUselessTernary = "error"
                                performance/noDelete = "off"
                                style/noNegationElse = "error"
                                style/noNonNullAssertion = "off"
                                style/noRestrictedGlobals = "error"
                                style/noShoutyConstants = "error"
                                style/noUnusedTemplateLiteral = "off"
                                style/useBlockStatements = "error"
                                style/useCollapsedElseIf = "error"
                                style/useForOf = "error"
                                style/useImportType = "off"
                                style/useNodejsImportProtocol = "error"
                                style/useNumberNamespace = "error"
                                style/useShorthandAssign = "error"
                                style/useShorthandFunctionType = "error"
                                style/useSingleCaseStatement = "error"
                                suspicious/noConsoleLog = "error"
                                suspicious/noRedeclare = "off"

Workspace:
  Open Documents:               0
```

### Rule name

lint/nursery/noUndeclaredDependencies

### Playground link

none

### Expected result

Does not report `declare module '*.whatever'` in `.d.ts` files

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by Sec-ant** [comment] 2024-03-18 13:09
I think this can be considered as a duplicate of #2074.

**Comment by arendjr** [comment] 2024-03-18 13:16
I think this may need some clarification. @ipanasenko did you declare modules somewhere inside `.d.ts` files and now you want those modules to be considered declared, so you can import them elsewhere? If so, I agree you will be best solution is the suggested allowlist in #2074, at least for the time being.

Or did you mean you get a diagnostic in the `declare module` statement in a `.d.ts` file itself? If so, that would be a separate issue.

**Comment by ipanasenko** [comment] 2024-03-18 13:34
Sorry, including screenshot. I want to tell TS that it's okay in import `.png` and `.scss` files:

![image](https://github.com/biomejs/biome/assets/576152/38611149-5a56-4229-b3f0-572c88a009bf)

**Comment by arendjr** [comment] 2024-03-18 15:22
Right, gotcha. I think `noUndeclaredDependencies` should indeed not apply to these at all.

**Closed** 2024-03-19 06:40 UTC
Labels: A-Linter, S-Bug-confirmed
