### ISSUE TITLE
💅 Problem when using style.useImportType and vue

### ISSUE THREAD

**Issue by richtera** [biomejs/biome#2251] opened 2024-03-31 20:36 UTC
### Environment information

```bash
❯ biome rage --linter             
CLI:
  Version:                      1.6.3
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           unset
  JS_RUNTIME_NAME:              unset
  NODE_PACKAGE_MANAGER:         unset

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Linter:
  Recommended:                  false
  All:                          false
  Rules:                        performance/noDelete = "off"
                                style/useImportType = "off"
                                suspicious/noConfusingVoidType = "off"
                                suspicious/noExplicitAny = "off"

Workspace:
  Open Documents:               0
```

### Rule name

useImportType

### Playground link

https://codesandbox.io/p/devbox/biome-starter-cbs-rky6zq?file=%2Fsrc%2Findex.js&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clufyzybf00053b6lcqfh5ofs%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clufyzybf00023b6lr4ohi4ud%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clufyzybf00033b6l2zkmgc61%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clufyzybf00043b6lxp58uz0a%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clufyzybf00023b6lr4ohi4ud%2522%253A%257B%2522id%2522%253A%2522clufyzybf00023b6lr4ohi4ud%2522%252C%2522activeTabId%2522%253A%2522clufz8nv900u03b6ljdgacaqn%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Felement1.vue%2522%252C%2522id%2522%253A%2522clufz8nv900u03b6ljdgacaqn%2522%252C%2522mode%2522%253A%2522temporary%2522%257D%255D%257D%252C%2522clufyzybf00043b6lxp58uz0a%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clufyzybf00043b6lxp58uz0a%2522%257D%252C%2522clufyzybf00033b6l2zkmgc61%2522%253A%257B%2522id%2522%253A%2522clufyzybf00033b6l2zkmgc61%2522%252C%2522activeTabId%2522%253A%2522clufz4o6a00ni3b6lxfm9hkgy%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clufz4o6a00ni3b6lxfm9hkgy%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clufz4o8w008ndjip0w1bbe9p%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Expected result

All tags should show up as "values" and not "types" only. Currently when using something like `<Input` in the dom section of vue it would not automatically flag as the values being used and the import statement would be changed to `import type ...` or `import { type Input }`. It does seem to work for some elements and I couldn't quite figure out when it would and wouldn't work. I have turned off useImportType and then things seem to work ok. I would prefer being able to turn on useImportType.
I was unable to reproduce it in the Playground link, but if was 100% reproducible with one of my elements.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by Sec-ant** [comment] 2024-04-01 00:16
Duplicate of #2239

**Closed by Sec-ant** 2024-04-01 00:16 UTC
