### ISSUE TITLE
☂️  Translate the website in Japanese 🇯🇵 

### ISSUE THREAD

**Issue by ematipico** [biomejs/biome#880] opened 2023-11-25 17:02 UTC
Coordination issue for translating the website in Japanese.

Upon more studying, I think we can push the changes directly to `main`.
 
Our documentation uses Starlight, and that's how we can enable i18n: https://starlight.astro.build/guides/i18n/

My advice is to take charge of **one page** at the time.

I leave the task/coordination/help in the capable hands of @nissy-dev @unvalley  and @TaKO8Ki !

**Comment by ematipico** [comment] 2023-11-25 17:06
cc @Gumichocopengin8 as you said you would like to help :)

**Comment by nissy-dev** [comment] 2023-11-26 03:23
Here is a list of the tasks that I currently have in mind.

- [ ] Modify `astro.config.js` and `src/content/docs` directory for i18n
    - see: https://starlight.astro.build/guides/i18n/#configure-i18n
- [ ] Translate Starlight’s UI
   - see: https://starlight.astro.build/guides/i18n/#translate-starlights-ui
- [ ] Translate src/content/docs
   - [ ] index.md
   - [ ] analyzer/index.md
   - [ ] formatter/index.mdx
   - [ ] guides/big-projects.mdx
   - [ ] guides/getting-started.mdx
   - [ ] guides/how-biome-works.mdx
   - [ ] guides/integrate-in-editor.mdx
   - [ ] guides/manual-installation.mdx
   - [ ] internals/architecture.mdx
   - [ ] internals/credits.mdx
   - [ ] internals/language-support.mdx
   - [ ] internals/philosophy.mdx
   - [ ] internals/versioning.mdx
   - [ ] recipes/continuous-integration.mdx
   - [ ] reference/cli.mdx
   - [ ] reference/configuration.mdx
   - [ ] reference/vscode.mdx
   - [ ] blog/annoucing-biome.mdx
   - [ ] blog/biome-v1.mdx
   - [ ] blog/index.mdx

The following automatically generated documents will not be translated here.
I think we need to think about what to do about these things separately.

- internals/changelog.mdx
- linter/index.mdx

**Comment by nissy-dev** [comment] 2023-11-26 03:34
@Gumichocopengin8 
Are you working on any tasks about translations? If not, it might be a good to have them do these tasks first.

**Comment by Gumichocopengin8** [comment] 2023-11-26 03:36
yeah i'm working on it. I'll make a PR shortly after translating the `404.md` and `index.mdx`

**Comment by nissy-dev** [comment] 2023-11-26 03:45
Thank you! I've marked you a task on my to-do list that I think you might be working on.

Since there are many things to translate, there may not be a need to make each Japanese translation so natural. It is recommended that you separate the PR and try to improve it later. This is OSS, someone may commit a better translation.

**Comment by Gumichocopengin8** [comment] 2023-11-26 03:46
@nissy-dev #887 is the first PR of the Japanese translation. There's one sentence I cannot come up with a good translation. Do you have any good idea?

**Comment by unvalley** [comment] 2023-11-26 04:54
Honestly, I'm not positive for translation. I think it requires maintenance cost, the language native can only contribute, cannot understand the translation quality if we are not the language speaker. 
Besides, I don't know how much this is required.

**Comment by chansuke** [comment] 2023-11-26 05:08
I am Japanese native and would like to help on this if it's possible.

**Comment by nissy-dev** [comment] 2023-11-26 08:43
@unvalley Basically, I think it's better to support if a new member will work this translation mainly!

I seem your concerns are mainly about maintenance costs and translation quality. I could understand this point but, I couldn't understand how serious these problems are compared to the benefits that translation brings. Could you explain more details…?

To be honest, there are many things we won't know until we try like translation needs, costs, and quality. So first of all, I want to respect the wishes of those who want to contribute. If the maintenance cost or translation quality becomes problem, I think we can decide to remove translated docs.

And then, this is not just a Japanese problem. I believe that by being translated into Japanese, there will be a movement to translate it into other languages as well, and the project has the potential to spread worldwide. In fact, [javascript-parser-in-rust](https://github.com/oxc-project/javascript-parser-in-rust) started being translated into other languages after it was translated into Japanese.

**Comment by unvalley** [comment] 2023-11-26 09:30
@nissy-dev 
Thank you for the explanation. Let's try it out and see how Japanese speakers react. I would be happy if we could also investigate how much having Japanese translations helped with the implementation in the future. I will also contribute as much as I can.

**Comment by Gumichocopengin8** [comment] 2023-11-26 09:45
@unvalley I understand your concerns and I also agree that maintenance cost could be expensive, but I believe there are more benefits than the cost, especially for Japanese people. I think lots of Japanese appreciate Japanese doc since some are not comfortable reading and seeing English even with translation tools. For example, [this user in discord](https://discord.com/channels/1132231889290285117/1132602492987908166/1178183416907321395) would appreciate Japanese doc. Discord is a good place to ask questions but if docs have the answer, it saves users and contributors time. Also, potentially we might get more users who use the translated languages.

**Comment by nissy-dev** [comment] 2023-11-26 12:31
> For instance, when a lint rule is implemented, we need to provide its translation in Japanese as well. It's not ideal to be unable to keep pace with original (English). 

I agree with this point. I updated the comments and excluded auto generated docs which were updated often from the scope. In the ESLint documentation, individual rules are not translated.

see: https://github.com/biomejs/biome/issues/880#issuecomment-1826477936

**Comment by Yuiki** [comment] 2023-11-26 13:29
This is great project! I'm also a native Japanese speaker, so I think I can make some contriutions.
I want to take `guides/getting-started.mdx` :)

**Comment by yossydev** [comment] 2023-11-26 13:48
Good! I would love to work on this one myself!

**Comment by nissy-dev** [comment] 2023-11-26 14:01
@Yuiki I assigned 👍 

@yossydev Which file do you translate? see https://github.com/biomejs/biome/issues/880#issuecomment-1826477936

**Comment by ematipico** [comment] 2023-11-26 20:19
@unvalley 

I agree with @nissy-dev here. As for personal experience, in the past I was more keen to provide translation for my fellow country mates for projects that had already translations.

Although you are right that this creates maintenance burden to us, and we should make sure we don't burnout. It's good that you called out this, thank you.

It's like an investment, we should do it and hope for the best. I believe this is the right time to do it! And if it doesn't go well, we can always revert.

**Comment by Gumichocopengin8** [comment] 2023-11-26 22:47
@nissy-dev can I work on `analyzer/index.md` and `formatter/index.mdx`?

**Comment by nissy-dev** [comment] 2023-11-27 00:39
@Gumichocopengin8  I assigned!

**Comment by yoshi2no** [comment] 2023-11-27 01:34
@nissy-dev 

Hi!
Can I take `internals/philosophy.mdx` ?

Thanks!

**Comment by hitohata** [comment] 2023-11-27 01:49
Hi @nissy-dev 
Could I take `internals/credits.mdx`?

Thanks.

**Comment by nissy-dev** [comment] 2023-11-27 02:52
@hitohata @yoshi2no I assigned!

**Comment by seo1nk** [comment] 2023-11-27 04:35
@nissy-dev 
Hi!
Can I take `internals/architecture.mdx` ?

**Comment by sakimyto** [comment] 2023-11-27 05:16
@nissy-dev 
can I take `reference/cli.mdx` & `reference/vscode.mdx`?

**Comment by Gumichocopengin8** [comment] 2023-11-27 06:44
I think only core contributors and maintainers can assign PRs to them as reviewer(s).

**Comment by TaKO8Ki** [comment] 2023-11-27 06:49
It might be a good idea to create a team, such as 'japanese-translation-reviewers', so that reviewers are automatically assigned when files under website/src/content/docs/ja/ are edited or new files are added.

**Comment by unvalley** [comment] 2023-11-27 06:53
> I think only core contributors and maintainers can assign PRs to them as reviewers.

Oops, I didn't know that.

**Comment by unvalley** [comment] 2023-11-27 06:56
@ematipico could you create a team `japanese-translation-reviewers` includes me, TaKO8Ki, nissy-dev?

**Comment by TaKO8Ki** [comment] 2023-11-27 07:00
@ematipico In addition, I would appreciate it if you could turn auto assiginment on if possible. ref: https://docs.github.com/en/organizations/organizing-members-into-teams/managing-code-review-settings-for-your-team#configuring-auto-assignment

**Comment by nissy-dev** [comment] 2023-11-27 07:05
@sakimyto @seo1nk I assigned!

**Comment by nissy-dev** [comment] 2023-11-27 07:10
I created the team https://github.com/orgs/biomejs/teams/japanese-translation-reviewers

**Comment by TaKO8Ki** [comment] 2023-11-27 07:19
The next step is to set this team as the code owners. I'll work on it.

**Comment by Naturalclar** [comment] 2023-11-27 07:46
@nissy-dev I'd like to work on `linter/index.mdx`

**Comment by TaKO8Ki** [comment] 2023-11-27 07:51
I've assigned you.

**Comment by nissy-dev** [comment] 2023-11-27 10:26
@yossydev I assigned!

**Comment by unvalley** [comment] 2023-11-27 10:48
I think we should decide some criteria for translation, for example
- should we insert spaces before or after an English word ?
- should we write the word by katakana (カタカナ) or alphatbet ?
- how about formatting? use Prettier,  introduce textlint?

@nissy-dev I would like to see you take the initiative, and off course I can help

**Comment by Conaclos** [comment] 2023-11-27 12:21
> auto

Have you some context for that? This seems not optimal because the assignment of the review is "randomly" assigned.

**Comment by TaKO8Ki** [comment] 2023-11-27 12:27
@ematipico 

As you said, the assignment of the review is "randomly" assigned, but as far as I know, auto assignment allows you to choose the number of people to assign. In this case, if you set it to three people, whether you choose round robin or load balance, I believe everyone will get assigned.

**Comment by TaKO8Ki** [comment] 2023-11-27 13:03
@unvalley @nissy-dev 
> I think it is ok to create some criteria using tools like linters and formatters. (I don't agree with creating criteria that cannot be guaranteed by tools.) And, I don't have personal opinions about the settings or criteria.

I share the same opinion. Introducing a tool like textlint might be good, but I also think it's acceptable to have some variation in translation methods without being too concerned about it.

**Comment by unvalley** [comment] 2023-11-27 13:05
Let's do that, I can be a bit pedantic about Japanese😅

**Comment by u-abyss** [comment] 2023-11-27 15:43
@nissy-dev I'd like to work on `guides/big-projects.mdx`!

**Comment by nissy-dev** [comment] 2023-11-27 15:48
@u-abyss  I assigned you!

**Comment by chansuke** [comment] 2023-11-27 16:00
@nissy-dev Thank you so much for your work! I'd like to take `manual-installation.mdx`

**Comment by TaKO8Ki** [comment] 2023-11-27 16:12
@chansuke I've assigned you :)

**Comment by ematipico** [comment] 2023-11-27 16:21
> @ematipico any plans to translate to Spanish? I could help on that.

You can open a GitHub discussion, and start the conversation there, so we can understand what that means for the project. Let's keep this issue only for coordinating among translators

**Comment by unvalley** [comment] 2023-11-28 04:09
Anyone interested in introducing textlint? It help us to providing polished translation.
We can discuss specific textlint rules or plugins on the PR will be created for.

**Comment by yossydev** [comment] 2023-11-28 04:10
@unvalley 
> Anyone interested in introducing textlint? It helps us to providing polished translation. We can discuss specific textlint rules or plugins on the PR will be created for.

I'm insanely interested!

**Comment by Yuiki** [comment] 2023-11-28 14:10
@nissy-dev 
We have a task labeled `Translate Starlight's UI` on our list. However, since Startlight already offers [Japanese default UI strings](https://github.com/withastro/starlight/blob/f82cb340532747aaadff451271df2d6a018d8231/packages/starlight/translations/ja.json#L20), I think we don't need to translate those. What do you think?

**Comment by Naoto-Ida** [comment] 2023-11-28 15:26
Anything unassigned that I can pick up? Would be happy to give back for all the awesomeness this tool offers!

**Comment by ematipico** [comment] 2023-11-28 16:12
Actually, something is interesting that we should implement. At the moment our lint rule pages are generated from source: 
for example the documentation of this page https://biomejs.dev/linter/rules/no-debugger/ is generated from 

https://github.com/biomejs/biome/blob/01309e8c837bf1147ac8a29cb185065bd331f3fc/crates/biome_js_analyze/src/analyzers/suspicious/no_debugger.rs#L12-L28

Ideally, we could come up with a **long-term** solution, where people can add new translations (e.g. Japanese, Spanish, etc.). This means that we have to come up with some, here's an example:

```rs

declare_rule! {
    /// Disallow the use of `debugger`
    ///
    /// ```md,jp
    ///  <TRANSLATED CONTENT HERE> 
    /// ```
    /// ## Examples
    ///
    /// ### Invalid
    ///
    /// ```js,expect_diagnostic
    /// debugger;
    /// ```
    ///
    /// ### Valid
    ///
    /// ```js
    /// const test = { debugger: 1 };
    /// test.debugger;
    ///```
    pub(crate) NoDebugger {
        version: "1.0.0",
        name: "noDebugger",
        recommended: true,
        fix_kind: FixKind::Unsafe,
    }
}
```

Then, we will have to update https://github.com/biomejs/biome/blob/main/xtask/lintdoc/src/main.rs to: 
- inspect `md` in the codeblock, 
-  extract the `jp`
- and finally, generate the file

**Comment by nissy-dev** [comment] 2023-11-29 00:50
@Yuiki 
> We have a task labeled Translate Starlight's UI on our list. However, since Startlight already offers [Japanese default UI strings](https://github.com/withastro/starlight/blob/f82cb340532747aaadff451271df2d6a018d8231/packages/starlight/translations/ja.json#L20), I think we don't need to translate those. What do you think?

Thank you for pointing out! I removed the task.

**Comment by nissy-dev** [comment] 2023-11-29 00:59
@Naoto-Ida

> Anything unassigned that I can pick up? It seems like I was late to the party, with the list being full of assignees. Would be happy to give back for all the awesomeness this tool offers!

Thanks! We have two options.

- Translate the blog post
  - Choose any of the mdx/md files from [here](https://github.com/biomejs/biome/tree/main/website/src/content/docs/blog) and translate it
  - If possible, biome-wins-prettier-challenge.md would be great!
- Read the translated docs and look for typos and broken links
  - These docs have already deployed and been accessible from https://biomejs.dev/ja/ etc.

**Comment by nissy-dev** [comment] 2023-11-29 04:27
@ematipico Thanks for comments on translating lint rules!

In this issue, we have excluded automatically generated translations from the scope due to our maintainer's burden. There are several reasons for that.

- It takes a lot of time to translate every rules and ESLint also does not translate the docs of each rule into Japanese
- Many rules are compatible with ESLint and familiar with many JS developers, so there may be less need for translation.
- It is common for Japanese translations to be proofread using tools such as [textlint](https://github.com/textlint/textlint), but it is difficult to use them for translations using Rust's comments, so that we're not able to reduce the review cost

I think we can discuss whether to translate automatically generated documents in another issue after the this issue is over.

**Comment by yossydev** [comment] 2023-11-29 10:04
@nissy-dev @unvalley 
Thanks for your time!
Regarding textlint, am I correct in assuming that you have specific rules in place and that you will issue a PR when it is ready to be configured? :eyes:.

**Comment by nissy-dev** [comment] 2023-11-29 12:42
@yossydev Thank you for your interest in implementing Textlint rules!

I would like you to select rules that are considered useful for translation and introduce textlint (and if possible, configure CI, etc.). When doing this, we recommend checking the settings of several OSS translation projects.

**Comment by yossydev** [comment] 2023-11-29 12:47
@nissy-dev 
Yes sir! Thank you!
I will set up the necessary rules and CIs and send out a PR!

**Comment by yossydev** [comment] 2023-12-01 05:48
@nissy-dev 
Currently I am getting a 404 on the Japanese version of the blog page (https://biomejs.dev/ja/blog). Should I modify the page so that it transitions once to https://biomejs.dev/blog?

**Comment by nissy-dev** [comment] 2023-12-02 04:47
@yossydev  Hmm, I don't think this redirect is wrong.This problem seems to be resolved by placing blog/index.mdx in ja docs.

And then, I think the problem is that the 404 feedback is not enough. The 404 page was probably not working properly in the first place because it was deployed to vercel, and the translation was also interrupted. see: #954 

However, since we replaced vercel with netlify just yesterday, the 404 page seems to be working properly. Therefore, it would be ideal to fix as follows.

- add blog/index.mdx in ja docs
- translate 404.md

**Comment by Gumichocopengin8** [comment] 2023-12-02 05:28
Made a PR #1010 to follow up with #954.

**Comment by Gumichocopengin8** [comment] 2023-12-02 05:55
I found a routing bug. I'm pretty sure it worked fine on Vercel, so the bug is introduced after switching to Netlify.
Here's the fix #1011

**Comment by yossydev** [comment] 2023-12-02 07:55
> @yossydev Hmm, I don't think this redirect is wrong.This problem seems to be resolved by placing blog/index.mdx in ja docs.
> 
> And then, I think the problem is that the 404 feedback is not enough. The 404 page was probably not working properly because it was deployed to vercel, and the translation was also interrupted. see: #954
> 
> However, since we replaced vercel with netlify just yesterday, the 404 page seems to be working properly. Therefore, it would be ideal to fix as follows.
> 
> * add blog/index.mdx in ja docs
> * translate 404.md

@nissy-dev 
I see! Thank you!
May I tackle the problem over there myself? :eyes:

"add blog/index.mdx in ja docs" ← Regarding this, should the content remain in English??
For example, there is a blog article called [Biome formatter wins the Prettier challenge](https://biomejs.dev/blog/biome-wins-prettier-challenge/), but is it okay if the title is still in English on the ja/blog page?

**Comment by nissy-dev** [comment] 2023-12-02 15:56
@yossydev When I just checked, the blog directory moved and blog/index.mdx itself was removed...
If it's easy to fix, I think you can change it to https://biomejs.dev/blog, but I don't think many people access the footer of the top page, so I think it's okay to just leave it as 404.

**Comment by Gumichocopengin8** [comment] 2023-12-02 22:19
<img width="1205" alt="image" src="https://github.com/biomejs/biome/assets/34010665/b09d0dce-cf0c-4101-861a-5f488b4f0dcf">

Don't we wanna add other sponsors or README sponsor info is outdated?

**Comment by ematipico** [comment] 2023-12-02 23:24
> <img width="1205" alt="image" src="https://github.com/biomejs/biome/assets/34010665/b09d0dce-cf0c-4101-861a-5f488b4f0dcf">
> 
> Don't we wanna add other sponsors or README sponsor info is outdated?

Only gold and platinum sponsors are featured on our website

**Comment by nissy-dev** [comment] 2023-12-03 14:48
@chansuke Yes! I assigned you.

**Comment by ematipico** [comment] 2023-12-04 16:13
That's great @zhoujian-official ! Feel free to create a PR to add those links , maybe with this markdown at the very end of the page:

```md
## Translations

- [<TITLE IN YOUR LANGUAGE>](LINK)
```

**Comment by nissy-dev** [comment] 2023-12-05 03:42
@ematipico 
> I think we should not translate our blog posts. Instead, we should let the community translate the blog posts in their platforms

Totally, I agree with your opinions. I removed the task related to blog translation from https://github.com/biomejs/biome/issues/880#issuecomment-1837311752

**Comment by nissy-dev** [comment] 2023-12-05 03:43
@yossydev 
> Translate formatter option philosophy page
> Can I do this myself?

Yes, but I recommend starting after the PR has been merged.

**Comment by nissy-dev** [comment] 2023-12-05 04:00
@Naturalclar Hi! How's the translation going? If you don't have time, you can also assign it to someone else.

**Comment by Naturalclar** [comment] 2023-12-05 04:06
@nissy-dev sorry for the late response! :pray: I'll send a PR by end of tomorrow.

**Comment by unvalley** [comment] 2023-12-05 14:03
We recently added the [Formatter Option Philosophy](https://biomejs.dev/ja/formatter/option-philosophy/). This is interesting part to know about biome's direction. Anyone interested in this translation?

**Comment by nissy-dev** [comment] 2023-12-05 15:15
I have already assigned it to @yossydev 
ref: https://github.com/biomejs/biome/issues/880#issuecomment-1837311752, https://github.com/biomejs/biome/issues/880#issuecomment-1838721470

**Comment by unvalley** [comment] 2023-12-05 15:41
Ah, sorry I missed that.

**Comment by nissy-dev** [comment] 2023-12-09 08:18
Since all the originally planned translations have been completed, I would like to close this issue. Thank you very much to everyone who helped with the translation!

**Closed** 2023-12-09 08:18 UTC
Labels: A-Website, A-Documenation

**Comment by ematipico** [comment] 2023-12-09 08:35
One last thing to do, I think, would be to translate the README.md :)

**Comment by nissy-dev** [comment] 2023-12-09 08:45
I created the new issue https://github.com/biomejs/biome/issues/1125
