### ISSUE TITLE
📝 Unbalanced braces in nested union type

### ISSUE THREAD

**Issue by awans** [biomejs/biome#2168] opened 2024-03-22 20:02 UTC
### Environment information

```bash
CLI:
  Version:                      1.6.2
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           unset
  JS_RUNTIME_NAME:              unset
  NODE_PACKAGE_MANAGER:         unset

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              true
  Organize imports disabled:    false
  VCS disabled:                 true

Formatter:
  Format with errors:           false
  Indent style:                 Space
  Indent size:                  0
  Indent width:                 4
  Line ending:                  Lf
  Line width:                   110
  Attribute position:           Auto
  Ignore:                       ["*/__snapshots__/*", "*.js", "*.d.ts"]
  Include:                      []

JavaScript Formatter:
  Enabled:                      true
  JSX quote style:              Double
  Quote properties:             AsNeeded
  Trailing comma:               All
  Semicolons:                   Always
  Arrow parentheses:            Always
  Bracket spacing:              false
  Bracket same line:            false
  Quote style:                  Single
  Indent style:                 unset
  Indent size:                  unset
  Indent width:                 unset
  Line ending:                  unset
  Line width:                   100
  Attribute position:           Auto

JSON Formatter:
  Enabled:                      false
  Indent style:                 unset
  Indent width:                 unset
  Indent size:                  unset
  Line ending:                  unset
  Line width:                   unset
  Trailing Commas:              unset

Workspace:
  Open Documents:               0
```

### Configuration

```JSON
{
    "linter": {
        "enabled": false
    },
    "formatter": {
        "enabled": true,
        "attributePosition": "auto",
        "formatWithErrors": false,
        "indentStyle": "space",
        "indentWidth": 4,
        "lineWidth": 110,
        "ignore": ["*/__snapshots__/*", "*.js", "*.d.ts"]
    },
    "javascript": {
        "formatter": {
            "enabled": true,
            "quoteStyle": "single",
            "bracketSpacing": false,
            "trailingComma": "all",
            "lineWidth": 100
        }
    },
    "json": {
        "formatter": {
            "enabled": false
        }
    }
}
```

### Playground link

https://biomejs.dev/playground/?lineWidth=120&indentStyle=space&indentWidth=4&bracketSpacing=false&code=dAB5AHAAZQAgAFIAZQBzAHUAbAB0ACAAPQAKACAAIAAgACAAfAAgAHsAdgBhAGwAaQBkADoAIABmAGEAbABzAGUAfQAKACAAIAAgACAAfAAgAHsACgAgACAAIAAgACAAIAAgACAAIAAgAHYAYQBsAGkAZAA6ACAAdAByAHUAZQA7AAoAIAAgACAAIAAgACAAIAAgACAAIABkAGEAdABhADoACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAfAAgAHsACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAbwB0AGgAZQByAFYAYQBsAHUAZQA6ACAAcwB0AHIAaQBuAGcAOwAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAfQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAB8ACAAewAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAB2AGEAbAB1AGUAOgAgAHMAdAByAGkAbgBnADsACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAH0AOwAKACAAIAAgACAAIAAgAH0AOwAKAA%3D%3D

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by Sec-ant** [comment] 2024-03-23 01:27
I copied the code from this issue and pasted it into the deploy preview of #2134, it seems that PR will also fix this issue.

**Comment by Sec-ant** [comment] 2024-03-24 02:07
Close as a duplicate of #2037, let's track the progress in PR #2134

**Closed by Sec-ant** 2024-03-24 02:07 UTC
