### ISSUE TITLE
🐛 Imports are not sorted

### ISSUE THREAD

**Issue by informeti** [biomejs/biome#3882] opened 2024-09-12 07:07 UTC
### VS Code version

1.92.2

### Extension version

2.3.0

### Biome version

1.8.3

### Operating system

- [X] Windows
- [ ] macOS
- [X] Linux

### Description

Formatting (on save, or manually) doesn't sort imports.
The extension also doesn't indicate any warning or error regarding import order.

However, `biome check` reports errors:

```
biome check main.ts
main.ts organizeImports ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ Import statements could be sorted:
  
     1    │ - import·type·{·Construct·}·from·"constructs";
     2    │ - import·{·App,·TerraformStack·}·from·"cdktf";
     3    │ - import·{·AzurermProvider·}·from·"@cdktf/provider-azurerm/lib/provider";
     4    │ - import·{·StorageBackend·}·from·"./src/storage-backend";
     5    │ - import·{·resourceGroup·}·from·"@cdktf/provider-azurerm";
        1 │ + import·{·resourceGroup·}·from·"@cdktf/provider-azurerm";
        2 │ + import·{·AzurermProvider·}·from·"@cdktf/provider-azurerm/lib/provider";
        3 │ + import·{·App,·TerraformStack·}·from·"cdktf";
        4 │ + import·type·{·Construct·}·from·"constructs";
        5 │ + import·{·StorageBackend·}·from·"./src/storage-backend";
```

### Steps to reproduce

Write a TypeScript file with wrongly sorted imports.

### Expected behavior

The extension should show a warning or error when the imports are not sorted as expected, and should offer a quickfix.

When formatting the document (manually or on save), the imports should be sorted.

### Does this issue occur when using the CLI directly?

No

**Comment by shayneo** [comment] 2024-09-13 20:24
> After upgrading to 1.9.0
> 
> ```
> "source.organizeImports": "explicit"
> ```
> 
> works for me.
> 
> ```
> "source.organizeImports.biome": "explicit"
> ```
> 
> does not.
> 
> my full codeActionsOnSave now is set to:
> 
> ```
> "editor.codeActionsOnSave": {
>     "source.organizeImports": "explicit",
>     "source.organizeImports.biome": "explicit",
>     "source.fixAll.biome": "explicit",
>     "quickfix.biome": "explicit"
> }
> ```
> 
> as a workaround

correction - this isn't actually working. It's using the editor's default sort order when I do that.

**Comment by jackTabsCode** [comment] 2024-09-14 02:06
> It's using the editor's default sort order when I do that.
Right, this is supplied by the Typescript language server. Biome's import sorting is different from Typescript's (for whatever reason), so while this will sort your imports in some way, `biome check` will fail-and the extension refuses to organize/sort imports right now.

**Comment by ematipico** [comment] 2024-09-14 04:29
I am sure the cause of the regression is https://github.com/biomejs/biome/pull/3731

**Comment by malininss** [comment] 2024-09-15 05:06
I use version 1.9 and
`"source.organizeImports.biome": "explicit"` still doesn't work for me.
`"source.organizeImports": "explicit"` works fine

**Comment by alimehasin** [comment] 2024-09-15 16:16
> I use the 1.9 version.
> `"source.organizeImports.biome": "explicit"` still doesn't work for me.
> `"source.organizeImports": "explicit"` works fine

This works for me, but now it also sort exports, which is not an expected behavior for me

**Comment by alimehasin** [comment] 2024-09-15 16:28
> Did you follow https://biomejs.dev/analyzer/import-sorting/#import-sorting-via-vscode-extension ?

We did, still formatting via the extension fails while formatting in the cli work

**Comment by ematipico** [comment] 2024-09-15 16:46
Duplicate of https://github.com/biomejs/biome/issues/3879

It will be fixed in the next patch

**Closed** 2024-09-15 16:46 UTC
Labels: A-LSP, S-Bug-confirmed

**Comment by ck-euan** [comment] 2024-09-16 11:17
> > The extension should show a warning or error when the imports are not sorted as expected, and should offer a quickfix.
> 
> This is by design. Import sorting is meant to work very much like formatting: you configure your IDE/editor to run it on save, and then you can use the CLI to enforce it wherever you want

@ematipico So is there no way to automate it?
I just reenabled import sorting for my project and now have hundreds of files to go through, do I have to manually save each one? 😅

**Comment by jackTabsCode** [comment] 2024-09-16 17:09
@ck-euan You'd run `biome check --write`

**Comment by ck-euan** [comment] 2024-09-17 09:22
@jackTabsCode For me imports never sort with the CLI I just get the error "Import statements could be sorted"

**Comment by ematipico** [comment] 2024-09-17 09:36
> @jackTabsCode For me imports never sort with the CLI I just get the error "Import statements could be sorted"

You need to use `--fix` to actually apply the sorting
