### ISSUE TITLE
🐛 eslint migration find/replace bug

### ISSUE THREAD

**Issue by mjgerace** [biomejs/biome#3079] opened 2024-06-05 19:30 UTC
### Environment information

```block
CLI:
  Version:                      1.8.0
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.12.2"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.5.0"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### What happened?

I make use of the eslint "extends" section, where I extend a few of my own rules like so:
```
  extends: [
    "@mjgerace/eslint-configs/base-vitest",
    "@mjgerace/eslint-configs/react",
    "@mjgerace/eslint-configs/graphql",
  ],
```

When running `npx @biomejs/biome migrate eslint --write`, I am hitting the following issue, repeated for every one of the extends imports above: 

```
✖ Migration has encountered an error: `node` was invoked to resolve '@mjgerace/eslint-config-eslint-configs/graphql'. This invocation failed with the following error:
    node:internal/modules/esm/resolve:854
      throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base), null);
            ^
    
    Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@mjgerace/eslint-config-eslint-configs' imported from /Users/mjgerace/repos/MjApp/app/[eval]
```

Something fascinating is happening here - somewhere in the migration script, it appears `biome` is seeing `@mjgerace/eslint-configs`, and transforming it to `@mjgerace/eslint-config-eslint-configs`. How bizarre!

### Expected result

The imports are left unchanged so that node can resolve them, as eslint does today.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by Conaclos** [comment] 2024-06-06 10:04
I tried to test your config with ESLint and it seems that it also fails.
Here my reproduction:

```shell
❯ npm init
❯ npm i -D --save-exact eslint@8.56.0
❯ mkdir -p node_modules/@mjgerace/eslint-configs
❯ cat node_modules/@mjgerace/eslint-configs/package.json
  {
    "name": "eslint-configs",
    "version": "1.0.0",
    "main": "index.js",
    "exports": {
      "./base-vitest": "./index.js"
    }
  }

❯ cat node_modules/@mjgerace/eslint-configs/index.js 
  module.exports = {}

❯ cat .eslintrc.json 
  {
    "extends": ["@mjgerace/eslint-configs/base-vitest"]
  }

❯ npx eslint -c .eslintrc.json 

  Oops! Something went wrong! :(

  ESLint: 8.56.0

  ESLint couldn't find the config "@mjgerace/eslint-configs/base-vitest" to extend from. Please check that the name of the config is correct.

  The config "@mjgerace/eslint-configs/base-vitest" was referenced from the config file in ".eslintrc.json".

  If you still have problems, please stop by https://eslint.org/chat/help to chat with the team.

❯ # Even the base config failed to be loaded:
❯ cat .eslintrc.json 
  {
    "extends": ["@mjgerace/eslint-configs"]
  }

❯ npx eslint -c .eslintrc.json 

  Oops! Something went wrong! :(

  ESLint: 8.56.0

  ESLint couldn't find the config "@mjgerace/eslint-configs" to extend from. Please check that the name of the config is correct.

  The config "@mjgerace/eslint-configs/base-vitest" was referenced from the config file in ".eslintrc.json".

  If you still have problems, please stop by https://eslint.org/chat/help to chat with the team.
```

**Comment by mjgerace** [comment] 2024-06-06 18:03
> I tried to test your config with ESLint and it seems that it also fails. Here my reproduction:

Let me get you more info. I can assure you this setup works and has worked for a while - perhaps not having that package defined in package.json (despite having it in node_modules) is causing this issue. Something about this works fine for me for vanilla eslint, again, this idea is completely unrelated from the weird path modification I see happening..

**Comment by Conaclos** [comment] 2024-06-06 20:59
> You can even test biome migrate to see what I am talking about (run it on your example!)

I know it will fail, and I will get the same error you got.

However, to be able to fix the issue, I must be sure that your example is valid in ESLint. My reproduction of your example shows that it is not valid in ESLint. Could you provide a reproduction that is valid for ESLint and invalid for Biome?

**Comment by Conaclos** [comment] 2024-06-24 13:21
I am not sure if it is a real issue. It seems that this also fails with ESLint. Closing because it is not actionable.

**Closed by Conaclos** 2024-06-24 13:21 UTC
Labels: S-Needs repro, S-Needs response

**Comment by mjgerace** [comment] 2024-06-25 18:34
@Conaclos I will follow up, this is a real issue. I will provide eevidence to reopen.

**Comment by TheSamsa** [comment] 2024-10-28 08:30
Hi there, I have the same Issue.
```
CLI:
  Version:                      1.9.4
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v22.9.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "yarn/1.22.19"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

package.json devDependency: `@samsa/eslint-config`
.eslintrc.js useage `extends: [ `@samsa/eslint-config/nestjs ]`

The command `yarn biome migrate eslint --write` throws:
```
Migration has encountered an error: `node` was invoked to resolve '@samsa/eslint-config-eslint-config/nestjs'. This invocation failed with the following error:
    node:internal/modules/esm/resolve:839
      throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base), null);
```
as you can see it prepends `eslint-config-` to the name of the module lookup.

I also looked at the biome code, and in file `crates/biome-cli/src/execute/migrate/eslint.rs` if I replace the line with:
`Cow::Owned(format!("{scope}/{scoped}"))` it returns the expected `@samsa/eslint-config/nestjs` String/Cow.
Maybe there is an additional check needed?

**Comment by Conaclos** [comment] 2024-10-28 09:11
> Oh btw, I can ensure this setup works in ESLint, It's beeing used this way for a while now.

This is an undocumented pattern in the ESLint docs. I guess we could accept it because some packages are actually using this.

**Comment by Conaclos** [comment] 2024-10-28 09:24
@TheSamsa Actually I already fixed it in https://github.com/biomejs/biome/issues/2705

**Comment by ematipico** [comment] 2024-10-28 09:58
> @TheSamsa Actually I already fixed it in https://github.com/biomejs/biome/issues/2705
> Which version of Biome are you using?
> 

1.9.4 based on the rage command

**Comment by Conaclos** [comment] 2024-10-28 10:06
@TheSamsa Could you provide a reproduction? `@samsa/eslint-config` is not published on npm...

**Comment by TheSamsa** [comment] 2024-10-28 10:09
Its version 1.9.4, the most recent one in yarnpkgs.
@Conaclos I will tomorrow if thats okay. I used my name as placeholder since I have to check if its okay with the company to share this.
I will ave to reproduce it on GH then, since its a private repository.

**Comment by TheSamsa** [comment] 2024-10-29 12:07
I've provided a public repo with the basics of the eslint-config stuff.
https://github.com/TheSamsa/eslint_config

**Comment by Conaclos** [comment] 2024-10-30 14:04
@TheSamsa Fixed in #4435

**Comment by TheSamsa** [comment] 2024-10-30 14:17
Brillian, thanks a lot!
I am really curious to test biome!

**Comment by Conaclos** [comment] 2024-10-30 15:58
@TheSamsa I released [a nightly version](https://github.com/biomejs/biome/releases/tag/cli%2Fv1.9.5-nightly.4713c52) if you want to try it.
