### ISSUE TITLE
🐛 Incorrect formatting with VSCode plugin: Wrong indentation

### ISSUE THREAD

**Issue by ryo0301** [biomejs/biome#443] opened 2023-09-28 09:19 UTC
### Environment information

```block
CLI:
  Version:                      1.2.2
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v18.17.1"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/9.6.7"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0

Discovering running Biome servers...

Running Biome Server: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

ℹ The client isn't connected to any server but rage discovered this running Biome server.

Server:
  Version:                      1.2.2
  Name:                         biome_lsp
  CPU Architecture:             aarch64
  OS:                           macos

Workspace:
  Open Documents:               0

Other Active Server Workspaces:

Workspace:
  Open Documents:               1
  Client Name:                  Visual Studio Code
  Client Version:               1.82.2
```

### What happened?

! The same source code won't reproduce
! Even if it could be reproduced, changing the file name would not reproduce it.

Adding a property to a class further indents the entire class
I have no choice but to save the file and reformat it with `biome format lib/stack1.ts -write`.

```
export class Stack1 extends cdk.Stack {
    public readonly output1: cdk.CfnOutput;
```

↓

```
export class Stack1 extends cdk.Stack {
        public readonly output1: cdk.CfnOutput;
        public readonly output2: cdk.CfnOutput;
```

### Expected result

Should not be indented

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment] 2023-09-28 11:45
Are you able to create a reproduction? Maybe with codesandbox or GitHub repository?

**Comment by nhedger** [comment] 2023-10-21 15:44
I tried reproducing this issue too, but could not either.

**Comment by ematipico** [comment] 2023-10-23 08:45
I am going to close it because of the lack of reproduction. Please create a new issue if you happen to arrive here

**Closed by ematipico** 2023-10-23 08:45 UTC
Labels: S-Needs repro
