### ISSUE TITLE
🐛 Biome does not use the config from each project in Multi-root Workspace in vscode

### ISSUE THREAD

**Issue by vimutti77** [biomejs/biome#2036] opened 2024-03-11 05:03 UTC
### Environment information

```block
CLI:
  Version:                      1.6.0
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           windows

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         unset
  JS_RUNTIME_VERSION:           "v20.10.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.2.3"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### What happened?

If we use [Multi-root Workspace](https://code.visualstudio.com/docs/editor/multi-root-workspaces) in vscode. Biome will not use the configs from each projects. It will use from the first project only.

1. Clone this repo https://github.com/vimutti77/biome-multi-root-workspace
2. Open `project.code-workspace` with vscode
3. See that each projects have different `biome.json`

![image](https://github.com/biomejs/biome/assets/27840664/9c4a621e-9df4-4628-97c9-8b5f80e8dcc9)
![image](https://github.com/biomejs/biome/assets/27840664/590e5bd9-1152-4553-a53e-0288409a0582)

4. In the project `backend`, open `src/index.js`. Biome reports issues correctly

![image](https://github.com/biomejs/biome/assets/27840664/68ea5736-65db-4f47-9341-34114369d4e1)

5. In the project `frontend`, open `src/index.js`. Biome still reports issues even if we disable the rule

![image](https://github.com/biomejs/biome/assets/27840664/a4a7d975-2559-46a1-800d-3fa24f931e10)

### Expected result

Biome should use the correct configs for each projects.
If we open the file in `backend`, It should use the config from `backend`
If we open the file in `frontend`, It should use the config from `frontend`

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by arendjr** [comment] 2024-03-11 07:30
I think this is a duplicate of: https://github.com/biomejs/biome/issues/1630

**Closed** 2024-03-15 06:31 UTC
