### ISSUE TITLE
🐛 When applying a fix with `lint/style/noUnusedTemplateLiteral` it doesn't respect formatter params like `javascript.formatter.quoteStyle`

### ISSUE THREAD

**Issue by dmythro** [biomejs/biome#1102] opened 2023-12-07 15:49 UTC
### Environment information

```block
CLI:
  Version:                      1.4.1
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.10.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.2.3"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### What happened?

1. Set `javascript.formatter.quoteProperties` to `single`, use recommended settings everywhere.
2. Have a file with unnecessary template literal of a string in TS/JS file instead of single quotes
3. Run `npx biome format --write .`

As a result, it formats this string inside a double quote, and probably also ignores the max line length as after `biome check --apply-unsafe .` it also formats a long string in a new line:

```ts
// before:
const test = {
  description: `Some long text here ...`,
}

// after:
const test = {
  description: "Some long text here ...",
}
```

### Expected result

String should use single quote, and respect line length. Expected result is:

```ts
const test = {
  description:
    'Some long text here ...',
}
```

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment] 2023-12-07 15:54
Hey @dmythro , we require a minimal reproduction for this issue. You can use our CBS https://codesandbox.io/p/devbox/biome-starter-cbs-rky6zq

**Comment by ematipico** [comment] 2024-01-04 12:22
Closing because we can't reproduce the issue

**Comment by dkAndFed** [comment] 2024-01-11 19:12
Experiencing the same issue on 1.5.1

Here's a CSB: https://codesandbox.io/p/devbox/festive-margulis-mg2plq

**Comment by ematipico** [comment] 2024-01-11 21:16
I believe this isn’t an issue but a feature request. The linter doesn’t have opinions on formatting choices. Also, if the formatter is disabled, users would expect different defaults.

**Comment by dkAndFed** [comment] 2024-01-12 08:31
FWIW from user point of view it's very confusing that when configuration is defined in a certain way you see one thing in the editor (when trying to apply the fix for example) and another when running a specific CLI command.

Argument can be made that seeing how it's "One toolchain for your web project" one would expect that the underlying tools should be aware of and respect each tool configuration.

**Comment by ematipico** [comment] 2024-01-12 09:00
> FWIW from user point of view it's very confusing that when configuration is defined in a certain way you see one thing in the editor (when trying to apply the fix for example) and another when running a specific CLI command.
> 
> Argument can be made that seeing how it's "One toolchain for your web project" one would expect that the underlying tools should be aware of and respect each tool configuration.

You're right, and I can agree with your point of view. I am not dismissing your argument.
This was a deliberate choice from the very beginning. Having our tools that work separately, so we can improve them without stomping on each other, then slowly join their features together and see how it plays out.

That's why I deem this as a feature request and not a bug.

**Closed** 2024-03-06 07:36 UTC
Labels: S-Needs repro
