### ISSUE TITLE
📎 Implement `useValidControlLabel` - `jsx-a11y/label-has-associated-control`

### ISSUE THREAD

**Issue by Conaclos** [biomejs/biome#2302] opened 2024-04-04 11:36 UTC
### Description

Implement [jsx-a11y/label-has-associated-control](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/label-has-associated-control.md).

**Want to contribute?** Lets you know you are interested! We will assign you to the issue to prevent several people to work on the same issue. Don't worry, we can unassign you later if you are no longer interested in the issue! Read our [contributing guide](https://github.com/biomejs/biome/blob/main/CONTRIBUTING.md) and [analyzer contributing guide](https://github.com/biomejs/biome/blob/main/crates/biome_analyze/CONTRIBUTING.md).

For now, I think we should skip the rule options.

Suggested name: `useValidControlLabel`

**Comment by ematipico** [comment] 2024-04-04 12:03
The rule triggers an error when using spread props. In Biome, we are less restrictive and we allow such cases in other rules, so we should do the same here.

**Comment by michellocana** [comment] 2024-05-21 12:26
@Conaclos, just accidentally stumbled upon here, I was working on #2610 which apparently is a duplicate of this one, should we close this or the other one?

**Closed** 2024-05-21 12:56 UTC
Labels: S-Help-wanted, A-Linter, L-JavaScript
