### ISSUE TITLE
🐛 `useExhaustiveDependencies` erroring on stable closures from React

### ISSUE THREAD

**Issue by imjordanxd** [biomejs/biome#632] opened 2023-10-30 09:30 UTC
### Environment information

```block
CLI:
  Version:                      1.3.1
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v18.18.2"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/8.12.1"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 false

Workspace:
  Open Documents:               0
```

### What happened?

Playground: https://biomejs.dev/playground/?indentStyle=space&quoteStyle=single&trailingComma=none&code=aQBtAHAAbwByAHQAIAAqACAAYQBzACAAUgBlAGEAYwB0ACAAZgByAG8AbQAgACcAcgBlAGEAYwB0ACcAOwAKAAoAZQB4AHAAbwByAHQAIABmAHUAbgBjAHQAaQBvAG4AIAB1AHMAZQBEAGEAdABhACgAKQAgAHsACgAgACAAYwBvAG4AcwB0ACAAWwAsACAAcwBlAHQAXQAgAD0AIABSAGUAYQBjAHQALgB1AHMAZQBTAHQAYQB0AGUAKABmAGEAbABzAGUAKQA7AAoAIAAgAGMAbwBuAHMAdAAgAFsALAAgAHMAdABhAHIAdABUAHIAYQBuAHMAaQB0AGkAbwBuAF0AIAA9ACAAUgBlAGEAYwB0AC4AdQBzAGUAVAByAGEAbgBzAGkAdABpAG8AbgAoACkAOwAKACAAIAAKACAAIABjAG8AbgBzAHQAIABvAG4AQwBsAGkAYwBrAEEAdwBhAHkATABpAHMAdABlAG4AZQByAEgAYQBuAGQAbABlAHIAIAA9ACAAUgBlAGEAYwB0AC4AdQBzAGUAQwBhAGwAbABiAGEAYwBrACgAKAApACAAPQA%2BACAAewAKACAAIAAgACAAcwB0AGEAcgB0AFQAcgBhAG4AcwBpAHQAaQBvAG4AKAAoACkAIAA9AD4AIAB7AAoAIAAgACAAIAAgACAAcwBlAHQAKAAoAHMAKQAgAD0APgAgACEAcwApADsACgAgACAAIAAgAH0AKQA7AAoAIAAgAH0ALAAgAFsAXQApADsACgB9AAoA

### Expected result

The closures returned from the out-of-the-box React hooks are stable and can be omitted from the deps array.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment] 2023-10-30 10:40
Thank you for reporting. Duplicate of https://github.com/biomejs/biome/issues/578

**Closed by ematipico** 2023-10-30 10:40 UTC
