### ISSUE TITLE
💅 `useStringLiterals` produce false recommendations

### ISSUE THREAD

**Issue by anonrig** [biomejs/biome#1192] opened 2023-12-14 15:53 UTC
### Environment information

```bash
CLI:
  Version:                      1.4.0
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "alacritty"
  JS_RUNTIME_VERSION:           "v20.10.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.2.3"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 false

Workspace:
  Open Documents:               0
```

### Rule name

useStringLiterals

### Playground link

N/A

### Expected result

For the following code:

```
function captureRandomMessage() {
  Sentry.captureMessage('Message no ' + (Date.now() + Math.random()));
}
```

It produces:

<img width="1341" alt="Screenshot 2023-12-14 at 10 53 24 AM" src="https://github.com/biomejs/biome/assets/1935246/ec67a8bc-7708-44f3-bc9a-fab867b8abc5">

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by n-gude** [comment] 2023-12-15 16:58
I'd like to try this.

**Comment by ematipico** [comment] 2023-12-15 17:48
Assigned it to you @n-gude 

The issue is a big misleading, the expected result should be:

```js
function captureRandomMessage() {
  Sentry.captureMessage(`Message no '${(Date.now() + Math.random())}`);
}
```

**Closed** 2024-01-07 12:30 UTC
Labels: A-Linter, L-JavaScript, S-Bug-confirmed
