### ISSUE TITLE
🐛 Processing panicked: no entry found for key

### ISSUE THREAD

**Issue by herkulano** [biomejs/biome#2723] opened 2024-05-05 12:17 UTC
### Environment information

```block
CLI:
  Version:                      1.7.2
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.12.2"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "pnpm/9.0.5"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### What happened?

Source Location: crates/biome_js_semantic/src/semantic_model/scope.rs:115:33
Thread Name: biome::worker_0
Message: no entry found for key

./apps/web/src/utils/types.ts internalError/panic  INTERNAL  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  × processing panicked: no entry found for key

```ts
// types.ts
import type { Language } from "..."

export type PLng = {
	lng: Language
}

export type Params<T> = {
	params: {
		[key in keyof T]: key extends keyof T ? T[key] : unknown
	}
}

export type SearchParams<T> = {
	searchParams: {
		[key in keyof T]: key extends keyof T ? T[key] : unknown
	}
}
```

### Expected result

Not to error

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by Sec-ant** [comment] 2024-05-05 12:19
This is a duplicate of #2683

**Closed by Sec-ant** 2024-05-05 12:19 UTC
