### ISSUE TITLE
🐛 internalError/panic: no entry found for key

### ISSUE THREAD

**Issue by gabrielmaldi** [biomejs/biome#2680] opened 2024-05-02 07:39 UTC
### Environment information

```block
CLI:
  Version:                      1.7.2
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.12.2"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "bun/1.1.7"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### What happened?

[Playground link](https://biomejs.dev/playground/?code=dAB5AHAAZQAgAFAAcgBpAG0AaQB0AGkAdgBlACAAPQAgAG4AdQBsAGwAIAB8ACAAdQBuAGQAZQBmAGkAbgBlAGQAIAB8ACAAcwB0AHIAaQBuAGcAIAB8ACAAbgB1AG0AYgBlAHIAIAB8ACAAYgBvAG8AbABlAGEAbgAgAHwAIABzAHkAbQBiAG8AbAAgAHwAIABiAGkAZwBpAG4AdAA7AAoACgB0AHkAcABlACAAQgB1AGkAbAB0AEkAbgBzACAAPQAgAFAAcgBpAG0AaQB0AGkAdgBlACAAfAAgAHYAbwBpAGQAIAB8ACAARABhAHQAZQAgAHwAIABSAGUAZwBFAHgAcAA7AAoACgB0AHkAcABlACAAUABhAHIAdABpAGEAbABEAGUAZQBwAE8AcAB0AGkAbwBuAHMAIAA9ACAAewAKACAAIAByAGUAYQBkAG8AbgBsAHkAIAByAGUAYwB1AHIAcwBlAEkAbgB0AG8AQQByAHIAYQB5AHMAPwA6ACAAYgBvAG8AbABlAGEAbgA7AAoAfQA7AAoACgB0AHkAcABlACAAUABhAHIAdABpAGEAbABEAGUAZQBwADwAVAAsACAATwBwAHQAaQBvAG4AcwAgAGUAeAB0AGUAbgBkAHMAIABQAGEAcgB0AGkAYQBsAEQAZQBlAHAATwBwAHQAaQBvAG4AcwAgAD0AIAB7AH0APgAgAD0AIABUACAAZQB4AHQAZQBuAGQAcwAKACAAIAB8ACAAQgB1AGkAbAB0AEkAbgBzAAoAIAAgAHwAIAAoACgALgAuAC4AYQByAGcAdQBtAGUAbgB0AHMAXwA6ACAAYQBuAHkAWwBdACkAIAA9AD4AIAB1AG4AawBuAG8AdwBuACkACgAgACAAfAAgACgAbgBlAHcAIAAoAAoAIAAgACAAIAAgACAALgAuAC4AYQByAGcAdQBtAGUAbgB0AHMAXwA6ACAAYQBuAHkAWwBdAAoAIAAgACAAIAApACAAPQA%2BACAAdQBuAGsAbgBvAHcAbgApAAoAIAAgAD8AIABUAAoAIAAgADoAIABUACAAZQB4AHQAZQBuAGQAcwAgAE0AYQBwADwAaQBuAGYAZQByACAASwBlAHkAVAB5AHAAZQAsACAAaQBuAGYAZQByACAAVgBhAGwAdQBlAFQAeQBwAGUAPgAKACAAIAAgACAAPwAgAFAAYQByAHQAaQBhAGwATQBhAHAARABlAGUAcAA8AEsAZQB5AFQAeQBwAGUALAAgAFYAYQBsAHUAZQBUAHkAcABlACwAIABPAHAAdABpAG8AbgBzAD4ACgAgACAAIAAgADoAIABUACAAZQB4AHQAZQBuAGQAcwAgAFMAZQB0ADwAaQBuAGYAZQByACAASQB0AGUAbQBUAHkAcABlAD4ACgAgACAAIAAgACAAIAA%2FACAAUABhAHIAdABpAGEAbABTAGUAdABEAGUAZQBwADwASQB0AGUAbQBUAHkAcABlACwAIABPAHAAdABpAG8AbgBzAD4ACgAgACAAIAAgACAAIAA6ACAAVAAgAGUAeAB0AGUAbgBkAHMAIABSAGUAYQBkAG8AbgBsAHkATQBhAHAAPABpAG4AZgBlAHIAIABLAGUAeQBUAHkAcABlACwAIABpAG4AZgBlAHIAIABWAGEAbAB1AGUAVAB5AHAAZQA%2BAAoAIAAgACAAIAAgACAAIAAgAD8AIABQAGEAcgB0AGkAYQBsAFIAZQBhAGQAbwBuAGwAeQBNAGEAcABEAGUAZQBwADwASwBlAHkAVAB5AHAAZQAsACAAVgBhAGwAdQBlAFQAeQBwAGUALAAgAE8AcAB0AGkAbwBuAHMAPgAKACAAIAAgACAAIAAgACAAIAA6ACAAVAAgAGUAeAB0AGUAbgBkAHMAIABSAGUAYQBkAG8AbgBsAHkAUwBlAHQAPABpAG4AZgBlAHIAIABJAHQAZQBtAFQAeQBwAGUAPgAKACAAIAAgACAAIAAgACAAIAAgACAAPwAgAFAAYQByAHQAaQBhAGwAUgBlAGEAZABvAG4AbAB5AFMAZQB0AEQAZQBlAHAAPABJAHQAZQBtAFQAeQBwAGUALAAgAE8AcAB0AGkAbwBuAHMAPgAKACAAIAAgACAAIAAgACAAIAAgACAAOgAgAFQAIABlAHgAdABlAG4AZABzACAAbwBiAGoAZQBjAHQACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAA%2FACAAVAAgAGUAeAB0AGUAbgBkAHMAIABSAGUAYQBkAG8AbgBsAHkAQQByAHIAYQB5ADwAaQBuAGYAZQByACAASQB0AGUAbQBUAHkAcABlAD4AIAAvAC8AIABUAGUAcwB0ACAAZgBvAHIAIABhAHIAcgBhAHkAcwAvAHQAdQBwAGwAZQBzACwAIABwAGUAcgAgAGgAdAB0AHAAcwA6AC8ALwBnAGkAdABoAHUAYgAuAGMAbwBtAC8AbQBpAGMAcgBvAHMAbwBmAHQALwBUAHkAcABlAFMAYwByAGkAcAB0AC8AaQBzAHMAdQBlAHMALwAzADUAMQA1ADYACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAPwAgAE8AcAB0AGkAbwBuAHMAWwAiAHIAZQBjAHUAcgBzAGUASQBuAHQAbwBBAHIAcgBhAHkAcwAiAF0AIABlAHgAdABlAG4AZABzACAAdAByAHUAZQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAPwAgAEkAdABlAG0AVAB5AHAAZQBbAF0AIABlAHgAdABlAG4AZABzACAAVAAgAC8ALwAgAFQAZQBzAHQAIABmAG8AcgAgAGEAcgByAGEAeQBzACAAKABuAG8AbgAtAHQAdQBwAGwAZQBzACkAIABzAHAAZQBjAGkAZgBpAGMAYQBsAGwAeQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAD8AIAByAGUAYQBkAG8AbgBsAHkAIABJAHQAZQBtAFQAeQBwAGUAWwBdACAAZQB4AHQAZQBuAGQAcwAgAFQAIAAvAC8AIABEAGkAZgBmAGUAcgBlAG4AdABpAGEAdABlACAAcgBlAGEAZABvAG4AbAB5ACAAYQBuAGQAIABtAHUAdABhAGIAbABlACAAYQByAHIAYQB5AHMACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAPwAgAFIAZQBhAGQAbwBuAGwAeQBBAHIAcgBhAHkAPABQAGEAcgB0AGkAYQBsAEQAZQBlAHAAPABJAHQAZQBtAFQAeQBwAGUAIAB8ACAAdQBuAGQAZQBmAGkAbgBlAGQALAAgAE8AcAB0AGkAbwBuAHMAPgA%2BAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgADoAIABBAHIAcgBhAHkAPABQAGEAcgB0AGkAYQBsAEQAZQBlAHAAPABJAHQAZQBtAFQAeQBwAGUAIAB8ACAAdQBuAGQAZQBmAGkAbgBlAGQALAAgAE8AcAB0AGkAbwBuAHMAPgA%2BAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAOgAgAFAAYQByAHQAaQBhAGwATwBiAGoAZQBjAHQARABlAGUAcAA8AFQALAAgAE8AcAB0AGkAbwBuAHMAPgAgAC8ALwAgAFQAdQBwAGwAZQBzACAAYgBlAGgAYQB2AGUAIABwAHIAbwBwAGUAcgBsAHkACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgADoAIABUACAALwAvACAASQBmACAAdABoAGUAeQAgAGQAbwBuACcAdAAgAG8AcAB0ACAAaQBuAHQAbwAgAGEAcgByAGEAeQAgAHQAZQBzAHQAaQBuAGcALAAgAGoAdQBzAHQAIAB1AHMAZQAgAHQAaABlACAAbwByAGkAZwBpAG4AYQBsACAAdAB5AHAAZQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAA6ACAAUABhAHIAdABpAGEAbABPAGIAagBlAGMAdABEAGUAZQBwADwAVAAsACAATwBwAHQAaQBvAG4AcwA%2BAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAOgAgAHUAbgBrAG4AbwB3AG4AOwAKAAoALwAqACoACgBTAGEAbQBlACAAYQBzACAAYABQAGEAcgB0AGkAYQBsAEQAZQBlAHAAYAAsACAAYgB1AHQAIABhAGMAYwBlAHAAdABzACAAbwBuAGwAeQAgAGAATQBhAHAAYABzACAAYQBuAGQAIABhAHMAIABpAG4AcAB1AHQAcwAuACAASQBuAHQAZQByAG4AYQBsACAAaABlAGwAcABlAHIAIABmAG8AcgAgAGAAUABhAHIAdABpAGEAbABEAGUAZQBwAGAALgAKACoALwAKAHQAeQBwAGUAIABQAGEAcgB0AGkAYQBsAE0AYQBwAEQAZQBlAHAAPABLAGUAeQBUAHkAcABlACwAIABWAGEAbAB1AGUAVAB5AHAAZQAsACAATwBwAHQAaQBvAG4AcwAgAGUAeAB0AGUAbgBkAHMAIABQAGEAcgB0AGkAYQBsAEQAZQBlAHAATwBwAHQAaQBvAG4AcwA%2BACAAPQAgAHsAfQAgACYAIABNAGEAcAA8AAoAIAAgAFAAYQByAHQAaQBhAGwARABlAGUAcAA8AEsAZQB5AFQAeQBwAGUALAAgAE8AcAB0AGkAbwBuAHMAPgAsAAoAIAAgAFAAYQByAHQAaQBhAGwARABlAGUAcAA8AFYAYQBsAHUAZQBUAHkAcABlACwAIABPAHAAdABpAG8AbgBzAD4ACgA%2BADsACgAKAC8AKgAqAAoAUwBhAG0AZQAgAGEAcwAgAGAAUABhAHIAdABpAGEAbABEAGUAZQBwAGAALAAgAGIAdQB0ACAAYQBjAGMAZQBwAHQAcwAgAG8AbgBsAHkAIABgAFMAZQB0AGAAcwAgAGEAcwAgAGkAbgBwAHUAdABzAC4AIABJAG4AdABlAHIAbgBhAGwAIABoAGUAbABwAGUAcgAgAGYAbwByACAAYABQAGEAcgB0AGkAYQBsAEQAZQBlAHAAYAAuAAoAKgAvAAoAdAB5AHAAZQAgAFAAYQByAHQAaQBhAGwAUwBlAHQARABlAGUAcAA8AFQALAAgAE8AcAB0AGkAbwBuAHMAIABlAHgAdABlAG4AZABzACAAUABhAHIAdABpAGEAbABEAGUAZQBwAE8AcAB0AGkAbwBuAHMAPgAgAD0AIAB7AH0AIAAmACAAUwBlAHQAPABQAGEAcgB0AGkAYQBsAEQAZQBlAHAAPABUACwAIABPAHAAdABpAG8AbgBzAD4APgA7AAoACgAvACoAKgAKAFMAYQBtAGUAIABhAHMAIABgAFAAYQByAHQAaQBhAGwARABlAGUAcABgACwAIABiAHUAdAAgAGEAYwBjAGUAcAB0AHMAIABvAG4AbAB5ACAAYABSAGUAYQBkAG8AbgBsAHkATQBhAHAAYABzACAAYQBzACAAaQBuAHAAdQB0AHMALgAgAEkAbgB0AGUAcgBuAGEAbAAgAGgAZQBsAHAAZQByACAAZgBvAHIAIABgAFAAYQByAHQAaQBhAGwARABlAGUAcABgAC4ACgAqAC8ACgB0AHkAcABlACAAUABhAHIAdABpAGEAbABSAGUAYQBkAG8AbgBsAHkATQBhAHAARABlAGUAcAA8AEsAZQB5AFQAeQBwAGUALAAgAFYAYQBsAHUAZQBUAHkAcABlACwAIABPAHAAdABpAG8AbgBzACAAZQB4AHQAZQBuAGQAcwAgAFAAYQByAHQAaQBhAGwARABlAGUAcABPAHAAdABpAG8AbgBzAD4AIAA9ACAAewB9ACAAJgAgAFIAZQBhAGQAbwBuAGwAeQBNAGEAcAA8AAoAIAAgAFAAYQByAHQAaQBhAGwARABlAGUAcAA8AEsAZQB5AFQAeQBwAGUALAAgAE8AcAB0AGkAbwBuAHMAPgAsAAoAIAAgAFAAYQByAHQAaQBhAGwARABlAGUAcAA8AFYAYQBsAHUAZQBUAHkAcABlACwAIABPAHAAdABpAG8AbgBzAD4ACgA%2BADsACgAKAC8AKgAqAAoAUwBhAG0AZQAgAGEAcwAgAGAAUABhAHIAdABpAGEAbABEAGUAZQBwAGAALAAgAGIAdQB0ACAAYQBjAGMAZQBwAHQAcwAgAG8AbgBsAHkAIABgAFIAZQBhAGQAbwBuAGwAeQBTAGUAdABgAHMAIABhAHMAIABpAG4AcAB1AHQAcwAuACAASQBuAHQAZQByAG4AYQBsACAAaABlAGwAcABlAHIAIABmAG8AcgAgAGAAUABhAHIAdABpAGEAbABEAGUAZQBwAGAALgAKACoALwAKAHQAeQBwAGUAIABQAGEAcgB0AGkAYQBsAFIAZQBhAGQAbwBuAGwAeQBTAGUAdABEAGUAZQBwADwAVAAsACAATwBwAHQAaQBvAG4AcwAgAGUAeAB0AGUAbgBkAHMAIABQAGEAcgB0AGkAYQBsAEQAZQBlAHAATwBwAHQAaQBvAG4AcwA%2BACAAPQAgAHsAfQAgACYAIABSAGUAYQBkAG8AbgBsAHkAUwBlAHQAPABQAGEAcgB0AGkAYQBsAEQAZQBlAHAAPABUACwAIABPAHAAdABpAG8AbgBzAD4APgA7AAoACgAvACoAKgAKAFMAYQBtAGUAIABhAHMAIABgAFAAYQByAHQAaQBhAGwARABlAGUAcABgACwAIABiAHUAdAAgAGEAYwBjAGUAcAB0AHMAIABvAG4AbAB5ACAAYABvAGIAagBlAGMAdABgAHMAIABhAHMAIABpAG4AcAB1AHQAcwAuACAASQBuAHQAZQByAG4AYQBsACAAaABlAGwAcABlAHIAIABmAG8AcgAgAGAAUABhAHIAdABpAGEAbABEAGUAZQBwAGAALgAKACoALwAKAHQAeQBwAGUAIABQAGEAcgB0AGkAYQBsAE8AYgBqAGUAYwB0AEQAZQBlAHAAPABPAGIAagBlAGMAdABUAHkAcABlACAAZQB4AHQAZQBuAGQAcwAgAG8AYgBqAGUAYwB0ACwAIABPAHAAdABpAG8AbgBzACAAZQB4AHQAZQBuAGQAcwAgAFAAYQByAHQAaQBhAGwARABlAGUAcABPAHAAdABpAG8AbgBzAD4AIAA9ACAAewAKACAAIABbAEsAZQB5AFQAeQBwAGUAIABpAG4AIABrAGUAeQBvAGYAIABPAGIAagBlAGMAdABUAHkAcABlAF0APwA6ACAAUABhAHIAdABpAGEAbABEAGUAZQBwADwATwBiAGoAZQBjAHQAVAB5AHAAZQBbAEsAZQB5AFQAeQBwAGUAXQAsACAATwBwAHQAaQBvAG4AcwA%2BADsACgB9ADsACgA%3D)

Running `biome check --formatter-enabled=false --organize-imports-enabled=false .` produces:

```
Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates/biome_js_semantic/src/semantic_model/scope.rs:115:33
Thread Name: biome::worker_10
Message: no entry found for key

./utils/typescript.ts internalError/panic  INTERNAL  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ processing panicked: no entry found for key

  ⚠ This diagnostic was derived from an internal Biome error. Potential bug, please report it if necessary.
```

<img width="834" alt="image" src="https://github.com/biomejs/biome/assets/3728897/c6a0d02c-20c0-41b8-996a-1f0a09e02ab4">

The playground doesn't seem to panic.

### Expected result

It should not throw an error.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by Sec-ant** [comment] 2024-05-02 08:04
Duplicate of #2659, there's a temp workaround for this error in that issue, please do check.

**Closed by Sec-ant** 2024-05-02 08:04 UTC
