### ISSUE TITLE
Use strict mode in arrow function

### ISSUE THREAD

**Issue by lethefrost** [biomejs/biome#1610] opened 2024-01-19 18:25 UTC
### Documentation URL

https://biomejs.dev/linter/rules/no-redundant-use-strict/

### Description

I have the following IIFE

```js
(() => {
    "use strict";
})();
```

and biome suggest that it's `Redundant use strict directive`. But I didn't see an explanation regarding this case in the [documentation](https://biomejs.dev/linter/rules/no-redundant-use-strict/), and after searching on Google I haven't found much discussion on this topic. Can anyone teach me why this is redundant, and probably add it to the document so that the others encountering the same issue would feel less confused? Your explanation would be greatly appreciated!

### Expectations

case for arrow function

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by nhedger** [comment] 2024-01-19 19:07
The [no-redundant-use-strict](https://biomejs.dev/linter/rules/no-redundant-use-strict/) rule kicks in because [JS modules are automatically strict](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#strict_mode_for_modules).


### CommonJS

If you create a `test.cjs` (CommonJS) file with the following contents, the rule will not kick in, unless you actually have a redundancy:

```cjs
// Rule won't kick in
(() => {
    "use strict";
})();
```

```cjs
// Rule will kick in
"use strict";
(() => {
    "use strict";
})();
```

```
test.cjs:3:5 lint/suspicious/noRedundantUseStrict  FIXABLE  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ Redundant use strict directive.
  
    1 │ "use strict";
    2 │ (() => {
  > 3 │     "use strict";
      │     ^^^^^^^^^^^^^
    4 │ })();
  
  ℹ This outer use strict directive already enables strict mode.
```

### JS Module

However, when using JS modules, the rule will kick in.

```mjs
(() => {
    "use strict";
})();
```

```
test.mjs:2:5 lint/suspicious/noRedundantUseStrict  FIXABLE  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ Redundant use strict directive.
  
    1 │ (() => {
  > 2 │     "use strict";
      │     ^^^^^^^^^^^^^
    3 │ })();
  
  ℹ The entire contents of JavaScript modules are automatically in strict mode, with no statement needed to initiate it.
```

## Biome's behavior

Biome seems to consider `.js` files as JS modules by default.

## Documentation

I agree with you that the documents should be clarified.

**Comment by nhedger** [comment] 2024-01-19 21:15
Unfortunately I don’t

**Comment by ematipico** [comment] 2024-01-19 21:47
That's the intended behaviour. The greatest majority of the code bases are modern, so we assume that `.js` files are modules. If not, you have two options:
- use a `.cjs` file
- suppress the rule 

We will make this rule smarter in the future.

**Comment by UtkarshVerma** [comment] 2024-02-14 18:42
> That's the intended behaviour. The greatest majority of the code bases are modern, so we assume that `.js` files are modules. If not, you have two options:
> 
> * use a `.cjs` file
> * suppress the rule
> 
> We will make this rule smarter in the future.

Is there any way I can mark my `.js` file as a CommonJS file? Why I am asking this because I am working on a plugin for Obsidian which expects a CommonJS `main.js` file. Having `biome` detect it as a CommonJS module would be really helpful.

**Comment by ematipico** [comment] 2024-02-14 18:53
Unfortunately, no. But as I said, soon we will be able to make the rule smarter.

Do you have a package.json?

**Comment by UtkarshVerma** [comment] 2024-02-14 19:10
Yes, I do.

**Comment by Conaclos** [comment] 2024-09-16 14:51
Is this now fixed?

**Closed** 2024-09-22 09:43 UTC
